### PR TITLE
Added speakers for GAMI-MIT Critical Data Speaker Event

### PR DESCRIPTION
**Pull request by SreekarMantena**

### CODE REVIEW

**Comment by tompollard** [comment]
Looks like there are some issues with this:

Screen Shot 2021-04-15 at 00 22 26

**Comment by Lucas-Mc** [comment]
Yeah I saw that too and let @SreekarMantena know

**Comment by Lucas-Mc** [comment]
I think the images should be put into `bhutan/s/` with the others

**Comment by Lucas-Mc** [comment]
And I think the issue with the formatting is due to inconsistent spacing and `|` usage

**Pull request merged**
