### PR TITLE
marta picture updated

### PR DESCRIPTION
**Pull request by theonesp**
- Marta wanted a new picture so I added it.

### CODE REVIEW

**Comment by theonesp** [comment]
- Marta wanted a new picture so I added it.

**Comment by tompollard** [comment]
are the files in the .picasaoriginals folder intentionally included? it looks like this is a temporary directory used by a graphics editor. no problem if so, just want to check.

**Comment by theonesp** [comment]
Exactly they are created by the graphic editor, they are not temporary but
not needed anyway.

Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Research
Scientist
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-235- 53 Carleton St.
Cambridge, MA 02139

[image: LinkedIn logo]
<https://www.linkedin.com/in/miguelangelarmengol/?locale=en_US>

**Comment by tompollard** [comment]
if they aren't needed, then is there are reason to commit them to the github repo?

**Comment by theonesp** [comment]
Actually picasa is hiding them, that's why they went through. They are
useful for me when retouching the pictures but not essential.

Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Research
Scientist
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-235- 53 Carleton St.
Cambridge, MA 02139

[image: LinkedIn logo]
<https://www.linkedin.com/in/miguelangelarmengol/?locale=en_US>

**Pull request merged**
