### PR TITLE
Courses style

### PR DESCRIPTION
**Pull request by theonesp**
course description updated (list of faculties and sign in button).
blog section renamed to events.

### CODE REVIEW

**Comment by tompollard** [comment]
It looks like things have got a bit mixed up, leading to some conflicts with the master branch. Please could you take a look? The merges probably don't need to be there and may be causing the issue.

**Comment by theonesp** [comment]
So commits I already pushed are being shown as new since I selected the 'squash and merge' button on my last pull request so everything looked _cleaner_.
My conflicting files 

- config.toml
- static/css/custom.css

are working fine in local and have a different code as the conflicting one being shown here.

**Comment by theonesp** [comment]
that would be great, see you then!
Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Research
Scientist
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-235- 53 Carleton St.
Cambridge, MA 02139

[image: LinkedIn logo]
<https://www.linkedin.com/in/miguelangelarmengol/?locale=en_US>

**Comment by theonesp** [comment]
created new branch for avoiding conflicts

**Pull request closed without merging**
