### PR TITLE
pictures and bios updated

### PR DESCRIPTION
**Pull request by theonesp**
Created this new branch since somehow my old branch diverged from the master branch, probably with the squashes.
Also in this new version I include the following changes:
- renamed blog to events.
- renamed the section 'what we do' to 'activities' as ken suggested.
- added new bios and pictures of the faculties.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks, much cleaner now. I've just tried building locally, and it's looking good. Just a few small things:

 - for me the events page (http://localhost:1313/events/) is empty (no events are listed). Should there be events listed on this page?
- on the front page () the content in the "The latest from MIT Critical Data" section has disappeared.
- In the footer, the "Recent posts" section is empty. Should there be something appearing here too (e.g. recent events)?
- At http://localhost:1313/activities/courses/, Shawn's image is missing (no placeholder or picture).

**Comment by theonesp** [comment]
Hi Tom, these 3 things

> - for me the events page (http://localhost:1313/events/) is empty (no events are listed). Should there be events listed on this page?
> - on the front page () the content in the "The latest from MIT Critical Data" section has disappeared.
> - In the footer, the "Recent posts" section is empty. Should there be something appearing here too (e.g. recent events)?

are related  to the rename of the blog to 'events'. the posts are there, and I changed the route but I'm still missing something since the section 'events' is not yet working as a blog.

> - At http://localhost:1313/activities/courses/, Shawn's image is missing (no placeholder or picture).

I'm going to fix this and update the pull request.

**Comment by tompollard** [comment]
merged! thanks miguel.

**Comment by theonesp** [comment]
thank you for your help!
Miguel

------------------------------

  [image: MIT][image: imes]

*Miguel Ángel Armengol de la Hoz **✉* <maarmeng@mit.edu> / Research
Scientist
*MIT - Institute for Medical Engineering and Science *
*Laboratory for Computational Physiology*
MIT, E25-235- 53 Carleton St.
Cambridge, MA 02139

[image: LinkedIn logo]
<https://www.linkedin.com/in/miguelangelarmengol/?locale=en_US>

**Pull request merged**
