### PR TITLE
bhutan seminar

### PR DESCRIPTION
**Pull request by kepaik**

### CODE REVIEW

**Comment by tompollard** [comment]
@Lucas-Mc please could you take a look at this and merge if you are happy?

**Comment by tompollard** [comment]
@kepaik if would be helpful for the reviewer if you could outline what changes you are making in the pull request.

**Comment by kepaik** [comment]
Changes: Added blog post: Bhutan Disaster Preparedness Event.
Plus images for the post.

Had to add a line in the config to enable html processing.  Might be able to exclude those changes.

Old website was compiled on Hugo 0.58 or earlier.  Some of the pages require the old version, so you shouldn't compile with the latest Hugo 0.82.  Should make sure course, consortium, and about pages are still in tact.

**Comment by Lucas-Mc** [comment]
I can't run this with Hugo 0.58 since I can't install it.... Homebrew installs like 0.81 as the only option, without any other tags since 0.58.0 is two years old and I tried to install the binary with Go@1.11 but I can't install that since it's not supported upstream through brew so I had to manually install Go@1.11 then tried to build from Github and the build needed Go@1.12 now it's not making the executable.... anyway, I may not be able to test this but I'll look at the code and others should make sure it works if they can

**Comment by kepaik** [comment]
Thanks for looking into this Lucas. I would normally promote using the later compiled versions, but I'm pretty sure it'll break several pages, e.g. course page and consortium.  

I'm in the process of updating the entire webpage, but wanted to get this Bhutan Seminar up as soon as possible, so if it compiles and is stable on an older version, I'd much appreciate a push to the servers.

**Pull request merged**
